import { relativeToAbsoluteDir, type RelativeDirection } from "../rules";
import data from "./board_A.json";

export interface HexPos {
  x: number;
  y: number;
}

interface BoardData {
  key: string;
  w: number;
  h: number;
  hexes: Record<string, HexPos>;
  neighbors: Record<string, (string | null)[]>;
}

/**
 * Hex centres and adjacency of one board, generated by
 * scripts/gen_board_data.py from the same computation as the realm's table,
 * so movement previews always agree with on-chain resolution.
 * Directions: 0=N 1=NE 2=SE 3=S 4=SW 5=NW.
 */
export class BoardMap {
  readonly key: string;
  readonly w: number;
  readonly h: number;
  private readonly hexes: Record<string, HexPos>;
  private readonly neighbors: Record<string, (string | null)[]>;

  constructor(d: BoardData) {
    this.key = d.key;
    this.w = d.w;
    this.h = d.h;
    this.hexes = d.hexes;
    this.neighbors = d.neighbors;
  }

  has(id: string): boolean {
    return Object.prototype.hasOwnProperty.call(this.hexes, id);
  }

  ids(): string[] {
    return Object.keys(this.hexes);
  }

  /** Pixel centre of a hex in the board image (1600×2232). */
  hexPos(id: string): HexPos {
    const p = this.hexes[id];
    if (!p) throw new Error(`unknown hex ${id}`);
    return p;
  }

  /** The hex id adjacent in an absolute direction, or null at the board edge. */
  neighbor(id: string, dir: number): string | null {
    const row = this.neighbors[id];
    if (!row || dir < 0 || dir > 5) return null;
    return row[dir] ?? null;
  }

  /** The hex id in a direction relative to a facing, or null at the edge. */
  relNeighbor(id: string, facing: number, rel: RelativeDirection): string | null {
    return this.neighbor(id, relativeToAbsoluteDir(facing, rel));
  }

  relNeighbors(id: string, facing: number, rels: RelativeDirection[]): { rel: RelativeDirection; hex: string | null }[] {
    return rels.map((rel) => ({ rel, hex: this.relNeighbor(id, facing, rel) }));
  }

  /** The nearest hex to a point in board pixels. */
  nearest(x: number, y: number): string {
    let best = "";
    let bestD = Infinity;
    for (const [id, p] of Object.entries(this.hexes)) {
      const d = (p.x - x) ** 2 + (p.y - y) ** 2;
      if (d < bestD) {
        bestD = d;
        best = id;
      }
    }
    return best;
  }
}

export const BOARD_A = new BoardMap(data as BoardData);
