#!/usr/bin/env python3
"""Generate the board A ("Corral") hex adjacency table for both the Gno realm
and the web client from assets/hex_grid.json.

Outputs (never edit by hand):
  gno.land/p/tbruyelle/gunslinger/hex/v0/board_a.gno
      sorted hex ids + 6-neighbour table as indices into that list (-1 = off-board)
      + axial coordinates (q, r) of every hex, for ranges and aim zones
  client/src/board/board_A.json
      {key, w, h, hexes: {id: {x, y, q, r}}, neighbors: {id: [6 x (id|null)]}}

Both files come from the same computation so the client's movement preview
and the realm's resolution can never disagree on adjacency.

Flat-top hexes tessellate in vertical columns:
  dir 0 = N  (up, -y)      1 = NE (up-right)    2 = SE (down-right)
  dir 3 = S  (down, +y)    4 = SW (down-left)   5 = NW (up-left)

Classification rule (same as bga/scripts/gen_board_data.py): for each hex, the
nearest other hex within MAX_DIST px whose bearing is within 30 degrees of a
direction's target angle is that direction's neighbour.
"""
import json
import math
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
GRID = os.path.join(ROOT, "assets", "hex_grid.json")
OUT_GNO = os.path.join(ROOT, "gno.land", "p", "tbruyelle", "gunslinger", "hex", "v0", "board_a.gno")
OUT_JSON = os.path.join(ROOT, "client", "src", "board", "board_A.json")

BOARD_KEY = "board_A"
BOARD_NAME = "A"
IMAGE_W, IMAGE_H = 1600, 2232
EXPECTED_HEXES = 137

# Target angle (degrees, screen coords y-down: 0=E, 90=S) for each direction.
DIR_ANGLE = {0: 270, 1: 330, 2: 30, 3: 90, 4: 150, 5: 210}
# Axial (q, r) step of each direction on a flat-top grid: q runs along the
# columns (east), r down the column; NE/SW and SE/NW are the diagonals.
DIR_AXIAL = {0: (0, -1), 1: (1, -1), 2: (1, 0), 3: (0, 1), 4: (-1, 1), 5: (-1, 0)}
MAX_DIST = 235.0  # a bit above the ~180-200px centre spacing
MAX_ANGLE_DIFF = 30.0


def ang_diff(a, b):
    d = abs(a - b) % 360
    return min(d, 360 - d)


def compute_neighbors(hexes):
    neighbors = {}
    for hid, (x, y) in hexes.items():
        best = {d: (None, math.inf) for d in range(6)}
        for oid, (ox, oy) in hexes.items():
            if oid == hid:
                continue
            dx, dy = ox - x, oy - y
            dist = math.hypot(dx, dy)
            if dist > MAX_DIST:
                continue
            ang = math.degrees(math.atan2(dy, dx)) % 360
            for d, target in DIR_ANGLE.items():
                if ang_diff(ang, target) <= MAX_ANGLE_DIFF and dist < best[d][1]:
                    best[d] = (oid, dist)
        neighbors[hid] = [best[d][0] for d in range(6)]
    return neighbors


def compute_axial(ids, neighbors):
    """Assigns axial coordinates by walking the adjacency from the first hex,
    and checks every edge agrees with the direction steps (a regular grid)."""
    origin = ids[0]
    coords = {origin: (0, 0)}
    queue = [origin]
    errors = []
    while queue:
        hid = queue.pop(0)
        q, r = coords[hid]
        for d, other in enumerate(neighbors[hid]):
            if other is None:
                continue
            dq, dr = DIR_AXIAL[d]
            want = (q + dq, r + dr)
            if other in coords:
                if coords[other] != want:
                    errors.append(f"irregular grid: {hid} -[{d}]-> {other} is at {coords[other]}, expected {want}")
            else:
                coords[other] = want
                queue.append(other)
    missing = [h for h in ids if h not in coords]
    if missing:
        errors.append(f"unreachable hexes: {missing}")
    return coords, errors


def check(hexes, neighbors):
    errors = []
    if len(hexes) != EXPECTED_HEXES:
        errors.append(f"expected {EXPECTED_HEXES} hexes, got {len(hexes)}")
    for hid, ns in neighbors.items():
        if not any(ns):
            errors.append(f"{hid} has no neighbours")
        for d, other in enumerate(ns):
            if other is None:
                continue
            back = neighbors[other][(d + 3) % 6]
            if back != hid:
                errors.append(f"asymmetric: {hid} -[{d}]-> {other} but {other} -[{(d + 3) % 6}]-> {back}")
    return errors


def write_gno(ids, index, neighbors, coords):
    lines = [
        "// Code generated by scripts/gen_board_data.py from assets/hex_grid.json. DO NOT EDIT.",
        "",
        "package hex",
        "",
        f'// A is board {BOARD_NAME} ("Corral"): {len(ids)} flat-top hexes in offset vertical columns.',
        "// ids is sorted so Index can binary-search it; nbr holds, for each hex, the",
        "// index of its neighbour in each of the 6 directions (N, NE, SE, S, SW, NW),",
        "// or -1 when the hex is on the board edge; qr holds its axial coordinates.",
        "var A = &Board{",
        f'\tname: "{BOARD_NAME}",',
        "\tids: []string{",
    ]
    for hid in ids:
        lines.append(f'\t\t"{hid}",')
    lines.append("\t},")
    lines.append("\tnbr: [][6]int{")
    for hid in ids:
        cells = ", ".join("-1" if n is None else str(index[n]) for n in neighbors[hid])
        lines.append(f"\t\t{{{cells}}}, // {hid}")
    lines.append("\t},")
    lines.append("\tqr: [][2]int{")
    for hid in ids:
        q, r = coords[hid]
        lines.append(f"\t\t{{{q}, {r}}}, // {hid}")
    lines.append("\t},")
    lines.append("}")
    lines.append("")
    os.makedirs(os.path.dirname(OUT_GNO), exist_ok=True)
    with open(OUT_GNO, "w") as f:
        f.write("\n".join(lines))
    return OUT_GNO


def write_json(ids, hexes, neighbors, coords):
    data = {
        "key": BOARD_KEY,
        "w": IMAGE_W,
        "h": IMAGE_H,
        "hexes": {hid: {"x": hexes[hid][0], "y": hexes[hid][1], "q": coords[hid][0], "r": coords[hid][1]} for hid in ids},
        "neighbors": {hid: neighbors[hid] for hid in ids},
    }
    os.makedirs(os.path.dirname(OUT_JSON), exist_ok=True)
    with open(OUT_JSON, "w") as f:
        json.dump(data, f, separators=(",", ":"))
        f.write("\n")
    return OUT_JSON


def main():
    grid = json.load(open(GRID))
    board = grid["boards"][BOARD_KEY]
    hexes = {h["id"]: (h["x"], h["y"]) for h in board["hexes"]}
    neighbors = compute_neighbors(hexes)

    errors = check(hexes, neighbors)
    if errors:
        for e in errors:
            print("error:", e, file=sys.stderr)
        sys.exit(1)

    ids = sorted(hexes)
    index = {hid: i for i, hid in enumerate(ids)}
    coords, errors = compute_axial(ids, neighbors)
    if errors:
        for e in errors:
            print("error:", e, file=sys.stderr)
        sys.exit(1)

    counts = {}
    for ns in neighbors.values():
        c = sum(1 for n in ns if n)
        counts[c] = counts.get(c, 0) + 1
    print("hexes:", len(ids))
    print("neighbour-count histogram (n_neighbours: n_hexes):", dict(sorted(counts.items())))
    print("sample A-F6 ->", neighbors["A-F6"])

    for path in (write_gno(ids, index, neighbors, coords), write_json(ids, hexes, neighbors, coords)):
        print("wrote", os.path.relpath(path, ROOT), f"({os.path.getsize(path)} bytes)")


if __name__ == "__main__":
    main()
